# Generated by Django 6.0.5 on 2026-05-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('ONE_TIME', 'One Time'), ('SUBSCRIPTION', 'Subscription')], max_length=20)),
                ('niche', models.CharField(choices=[('solar-usa', 'Solar USA'), ('solar-uk', 'Solar UK'), ('solar-ca', 'Solar Canada'), ('solar-au', 'Solar Australia'), ('sweeps-auto', 'Sweepstakes Auto'), ('sweeps-health', 'Sweepstakes Health'), ('sweeps-medicare', 'Sweepstakes Medicare'), ('sweeps-home', 'Sweepstakes Home'), ('sweeps-life', 'Sweepstakes Life'), ('sweeps-debt', 'Sweepstakes Debt'), ('sweeps-generic', 'Sweepstakes Generic')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_lead', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('VOID', 'Void')], default='UNPAID', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='clients.client')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='billing.order')),
            ],
        ),
    ]
