from django.core.management.base import BaseCommand

from apps.groups.models import FacebookGroup

GROUPS = [
    {"name": "Data leads", "group_url": "https://www.facebook.com/groups/databaseformarketing", "group_type": "data_leads", "members": 11300, "quality": "very_good", "is_active": True, "owner_name": "Timothy Dann", "owner_url": "https://www.facebook.com/timothy.dann.2024/", "admin_1": "Timothy Dann", "admin_2": "Lead Publisher", "admin_3": "Sharaf Mahbub", "agent_name": "Nabil, Iram, Siam", "backup_url": ""},
    {"name": "Email and Number Lists for Marketing Campaign", "group_url": "https://www.facebook.com/groups/607389663817215/", "group_type": "cpa_affiliate", "members": 8300, "quality": "good", "is_active": True, "owner_name": "AHS Nabs", "owner_url": "https://www.facebook.com/groups/607389663817215/user/100073735286618", "admin_1": "A H S Nabs", "admin_2": "Data Provider", "admin_3": "", "agent_name": "Sayem, Shaeed", "backup_url": ""},
    {"name": "DATA VENDOR EXCLUSIVE", "group_url": "", "group_type": "data_leads", "members": 7500, "quality": "good", "is_active": True, "owner_name": "William Alice", "owner_url": "https://www.facebook.com/profile.php?id=61560334143296", "admin_1": "William Alice", "admin_2": "Kevin Mitnick Data Network", "admin_3": "", "agent_name": "Pavel, Arif", "backup_url": ""},
    {"name": "Tech Sales Email Leads Provider", "group_url": "https://www.facebook.com/share/g/1CR1z94Eet/", "group_type": "data_leads", "members": 6800, "quality": "average", "is_active": True, "owner_name": "AKM Aditto", "owner_url": "", "admin_1": "Jonas Weber", "admin_2": "Arjun Desai", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "Data Buy/Sell Market", "group_url": "https://www.facebook.com/groups/424391656534575/", "group_type": "data_leads", "members": 6700, "quality": "good", "is_active": True, "owner_name": "Data Provider", "owner_url": "https://www.facebook.com/groups/424391656534575/user/100049229118890", "admin_1": "Data Provider", "admin_2": "Daniel Cook", "admin_3": "Timothy Dann", "agent_name": "Shaeed, Iram", "backup_url": ""},
    {"name": "Active Email Leads Buy and Sell", "group_url": "https://www.facebook.com/groups/1104306947729329/", "group_type": "data_leads", "members": 4000, "quality": "average", "is_active": True, "owner_name": "William Alice", "owner_url": "https://www.facebook.com/profile.php?id=61560334143296", "admin_1": "William Alice", "admin_2": "Kishan Reddy", "admin_3": "Kevin Mitnick Data Network", "agent_name": "Pavel, Arif, Shafi, Tanjnil", "backup_url": ""},
    {"name": "MailRaptor SMTP/RDP/Gmail_api/Blasting_system/sending_system", "group_url": "https://www.facebook.com/groups/mailraptor/", "group_type": "data_leads", "members": 3500, "quality": "average", "is_active": True, "owner_name": "Soham Sen", "owner_url": "https://www.facebook.com/Subaru.leads/", "admin_1": "Data Provider", "admin_2": "William Alice", "admin_3": "Franz Bonaparta", "agent_name": "Abir, Shaeed, Pavel, Shafi", "backup_url": "https://www.facebook.com/groups/mailraptorsmtprdpgmailapiblastingsystemsend/"},
    {"name": "Leads Buy & Sell Arena", "group_url": "", "group_type": "data_leads", "members": 3300, "quality": "average", "is_active": True, "owner_name": "Soham Sen", "owner_url": "https://www.facebook.com/Subaru.leads/", "admin_1": "Lead Publisher", "admin_2": "Data Provider", "admin_3": "Timothy Dann", "agent_name": "Nabil, Shaeed, Iram, Abir", "backup_url": "https://www.facebook.com/groups/leadsbuysellarena2.0/"},
    {"name": "USA leads Buy & Sell", "group_url": "https://www.facebook.com/groups/usaleadsbuysell", "group_type": "data_leads", "members": 3200, "quality": "average", "is_active": True, "owner_name": "Timothy Dann", "owner_url": "https://www.facebook.com/timothy.dann.2024/", "admin_1": "Timothy Dann", "admin_2": "", "admin_3": "", "agent_name": "Iram", "backup_url": ""},
    {"name": "Email Data Blasting HUB", "group_url": "https://www.facebook.com/groups/emaildatablustinghub", "group_type": "email_tech", "members": 3100, "quality": "average", "is_active": True, "owner_name": "Soham Sen", "owner_url": "https://www.facebook.com/Subaru.leads/", "admin_1": "Leads Man", "admin_2": "Will Jacks", "admin_3": "Franz Bonaparta", "agent_name": "Abir, Siam, Rafin, Shafi", "backup_url": "https://www.facebook.com/groups/emaildatablastinghub2.0/"},
    {"name": "World wide data buy sell network", "group_url": "https://www.facebook.com/groups/worldwidedatabuysellnetwork/", "group_type": "data_leads", "members": 2800, "quality": "below_average", "is_active": True, "owner_name": "Leads Publisher", "owner_url": "https://www.facebook.com/profile.php?id=100085964365613", "admin_1": "Leads Publisher", "admin_2": "", "admin_3": "", "agent_name": "Nabil", "backup_url": ""},
    {"name": "Cold email market (buy & sell)", "group_url": "https://www.facebook.com/groups/coldemailmarket", "group_type": "data_leads", "members": 2100, "quality": "below_average", "is_active": True, "owner_name": "AHS Nabs", "owner_url": "https://www.facebook.com/a.h.s.nabs", "admin_1": "A H S Nabs", "admin_2": "Kishan Reddy", "admin_3": "Franz Bonaparta", "agent_name": "Sayem, Shafi", "backup_url": ""},
    {"name": "DATA VENDOR", "group_url": "https://www.facebook.com/groups/751513217459558/", "group_type": "data_leads", "members": 1800, "quality": "below_average", "is_active": True, "owner_name": "Faizan Taisir", "owner_url": "https://www.facebook.com/groups/751513217459558/user/100055212361074", "admin_1": "Faizan Taisir", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "Email Data Vendor", "group_url": "https://www.facebook.com/groups/emaildatavendor/", "group_type": "data_leads", "members": 1800, "quality": "below_average", "is_active": True, "owner_name": "No Admin", "owner_url": "", "admin_1": "", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "Verified Data buy & Sale", "group_url": "https://www.facebook.com/groups/verifieddatabuysell/", "group_type": "data_leads", "members": 1700, "quality": "below_average", "is_active": True, "owner_name": "Previous ID Disable", "owner_url": "", "admin_1": "", "admin_2": "", "admin_3": "", "agent_name": "Fahim", "backup_url": ""},
    {"name": "Email Data and Lead Solution", "group_url": "https://www.facebook.com/groups/1861029344351811", "group_type": "data_leads", "members": 1600, "quality": "bad", "is_active": True, "owner_name": "Data Lead Vendor", "owner_url": "https://www.facebook.com/data.lead.vendor/", "admin_1": "Data Lead Vendor", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "PRO EMAIL GROWTH HUB", "group_url": "https://www.facebook.com/groups/1102604361817067", "group_type": "email_tech", "members": 1300, "quality": "below_average", "is_active": True, "owner_name": "Timothy Dann", "owner_url": "https://www.facebook.com/", "admin_1": "Timothy Dann", "admin_2": "Franz Bonaparta", "admin_3": "", "agent_name": "Iram, Shafi", "backup_url": ""},
    {"name": "Email Blasting Data & Leads Zone (Buyers & Vendors)", "group_url": "https://www.facebook.com/share/g/1XBwFrNnFH/", "group_type": "data_leads", "members": 1300, "quality": "below_average", "is_active": True, "owner_name": "Kevin Mitnick Data Network", "owner_url": "https://www.facebook.com/profile.php?id=61568992230171", "admin_1": "Lead Publisher", "admin_2": "Kevin Mitnick Data Network", "admin_3": "Adity Devnath", "agent_name": "Nabil, Arif, Rafin", "backup_url": ""},
    {"name": "Alpha Data & Leads", "group_url": "https://www.facebook.com/groups/alphadataleads/", "group_type": "data_leads", "members": 1200, "quality": "below_average", "is_active": True, "owner_name": "Oscar Atom", "owner_url": "https://www.facebook.com/oscar.atom.2024", "admin_1": "Oscar Atom", "admin_2": "", "admin_3": "", "agent_name": "Abir", "backup_url": ""},
    {"name": "Marketing Leaders (Jason)", "group_url": "https://www.facebook.com/groups/marketingdataleads/", "group_type": "data_leads", "members": 1000, "quality": "below_average", "is_active": True, "owner_name": "Jason B. Cook", "owner_url": "https://www.facebook.com/", "admin_1": "Jason B. Cook", "admin_2": "Franz Bonaparta", "admin_3": "", "agent_name": "Iram, Shafi", "backup_url": ""},
    {"name": "Tech Support Legit Buyer & Seller Community", "group_url": "https://www.facebook.com/groups/2692447947760984/", "group_type": "data_leads", "members": 1000, "quality": "below_average", "is_active": True, "owner_name": "William Alice", "owner_url": "https://www.facebook.com/profile.php?id=61560334143296", "admin_1": "William Alice", "admin_2": "Franz Bonaparta", "admin_3": "", "agent_name": "Shafi, Pavel", "backup_url": ""},
    {"name": "Marketing Leaders", "group_url": "https://www.facebook.com/groups/marketingdataleads/", "group_type": "data_leads", "members": 996, "quality": "bad", "is_active": True, "owner_name": "William Alice", "owner_url": "https://www.facebook.com/profile.php?id=61560334143296", "admin_1": "William Alice", "admin_2": "", "admin_3": "", "agent_name": "Pavel", "backup_url": ""},
    {"name": "Active Data & Leads", "group_url": "https://www.facebook.com/groups/activedataleads", "group_type": "data_leads", "members": 959, "quality": "bad", "is_active": True, "owner_name": "Soham Sen", "owner_url": "https://www.facebook.com/Subaru.leads/", "admin_1": "Daniel Cook", "admin_2": "Leads Man", "admin_3": "Arif", "agent_name": "Abir, Siam, Arif, Shaheed", "backup_url": "https://www.facebook.com/groups/activedataleads2.0/"},
    {"name": "Data House (leads buy and sell)", "group_url": "https://www.facebook.com/groups/data.house.buynsell/", "group_type": "data_leads", "members": 947, "quality": "bad", "is_active": True, "owner_name": "Aditya Debnath", "owner_url": "https://www.facebook.com/share/18kfvrche8/", "admin_1": "Aditya Debnath", "admin_2": "William Alice", "admin_3": "Franz Bonaparta", "agent_name": "Rafin, Shafi", "backup_url": ""},
    {"name": "Best Quality data Buy/Sale Network", "group_url": "https://www.facebook.com/groups/1057704779126183/", "group_type": "data_leads", "members": 891, "quality": "bad", "is_active": True, "owner_name": "Lead Publisher", "owner_url": "https://www.facebook.com/profile.php?id=100085964365613", "admin_1": "Lead Publisher", "admin_2": "", "admin_3": "", "agent_name": "Nabil", "backup_url": ""},
    {"name": "Data Buy/Sell Boosters Community", "group_url": "https://www.facebook.com/groups/2002795760209396/", "group_type": "data_leads", "members": 802, "quality": "worst", "is_active": True, "owner_name": "William Alice", "owner_url": "https://www.facebook.com/profile.php?id=61560334143296", "admin_1": "William Alice", "admin_2": "Franz Bonaparta", "admin_3": "", "agent_name": "Pavel, Shafi", "backup_url": ""},
    {"name": "Tech-Email Data Marketing Group", "group_url": "https://www.facebook.com/groups/emailtechsupport", "group_type": "data_leads", "members": 722, "quality": "bad", "is_active": True, "owner_name": "William Alice", "owner_url": "https://www.facebook.com/profile.php?id=61560334143296", "admin_1": "William Alice", "admin_2": "", "admin_3": "", "agent_name": "Pavel, Arif", "backup_url": ""},
    {"name": "TELE LEADS - USA | UK | Australia | Canada | UAE", "group_url": "https://www.facebook.com/groups/1855286358735692/", "group_type": "telemarketing", "members": 689, "quality": "bad", "is_active": True, "owner_name": "Previous ID Disable", "owner_url": "", "admin_1": "", "admin_2": "", "admin_3": "", "agent_name": "Fahim", "backup_url": ""},
    {"name": "Active Data & Leads Community", "group_url": "https://www.facebook.com/groups/dataleadscommunity", "group_type": "data_leads", "members": 673, "quality": "bad", "is_active": True, "owner_name": "Quality Data HUb", "owner_url": "https://www.facebook.com/Qualitydatahub/", "admin_1": "Quality Data HUb", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "UK/AUS/NZ/CAN EMAIL-COLD-CALLING-SMISHING DATA & LEADS", "group_url": "https://www.facebook.com/groups/719919527312052/", "group_type": "data_leads", "members": 669, "quality": "bad", "is_active": True, "owner_name": "Data Provider", "owner_url": "https://www.facebook.com/fairoz.fardin.5/", "admin_1": "Data Provider", "admin_2": "", "admin_3": "", "agent_name": "Shaheed", "backup_url": ""},
    {"name": "Leads Hub World Wide (Buy and Sell)", "group_url": "https://www.facebook.com/groups/leads.hub.ww/", "group_type": "data_leads", "members": 615, "quality": "bad", "is_active": True, "owner_name": "Franz Bonaparta", "owner_url": "https://www.facebook.com/profile.php?id=61578056373952", "admin_1": "Franz Bonaparta", "admin_2": "", "admin_3": "", "agent_name": "Shafi, Arif", "backup_url": ""},
    {"name": "All kind of Tech-Support Provider", "group_url": "https://www.facebook.com/groups/techsupportprovider/", "group_type": "data_leads", "members": 597, "quality": "bad", "is_active": True, "owner_name": "William Alice", "owner_url": "https://www.facebook.com/profile.php?id=61560334143296", "admin_1": "William Alice", "admin_2": "Franz Bonaparta", "admin_3": "", "agent_name": "Shafi, Arif", "backup_url": ""},
    {"name": "Secured SMTP/RDP/gmail_api/Blasting and Sending System Data", "group_url": "https://www.facebook.com/groups/securedsmtprdpgmailapiblastingandsendingsy/", "group_type": "data_leads", "members": 476, "quality": "worst", "is_active": True, "owner_name": "William Alice", "owner_url": "https://www.facebook.com/profile.php?id=61560334143296", "admin_1": "William Alice", "admin_2": "Franz Bonaparta", "admin_3": "", "agent_name": "Pavel, Shafi", "backup_url": ""},
    {"name": "Data & Leads Seekers", "group_url": "https://www.facebook.com/share/g/1CUb6F67do/", "group_type": "data_leads", "members": 470, "quality": "below_average", "is_active": True, "owner_name": "Ameet Sharma", "owner_url": "https://www.facebook.com/share/1E7JeTV2fs/", "admin_1": "Ameet Sharma", "admin_2": "Murtasim Khan", "admin_3": "Muhammad Nawaz", "agent_name": "Jisan", "backup_url": ""},
    {"name": "Leads Man Data & Leads Community", "group_url": "https://www.facebook.com/groups/1498050801401730/", "group_type": "review", "members": 451, "quality": "worst", "is_active": True, "owner_name": "Leads Man", "owner_url": "ID DISABLED", "admin_1": "", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "Elite Data & Lead Gen Strategy", "group_url": "https://www.facebook.com/groups/1780533749289039", "group_type": "data_leads", "members": 277, "quality": "below_average", "is_active": True, "owner_name": "Rizwan Ahmed", "owner_url": "https://www.facebook.com/profile.php?id=61585962414832", "admin_1": "Robert William", "admin_2": "", "admin_3": "", "agent_name": "Rat", "backup_url": ""},
    {"name": "The Data Drivers", "group_url": "https://www.facebook.com/groups/2217050372121748/", "group_type": "data_leads", "members": 222, "quality": "worst", "is_active": True, "owner_name": "Leads Man", "owner_url": "https://www.facebook.com/profile.php?id=61589129182528", "admin_1": "Franz Bonaparta", "admin_2": "", "admin_3": "", "agent_name": "Shafi, Arif, Siam", "backup_url": ""},
    {"name": "Email Data Storehouse", "group_url": "https://www.facebook.com/share/g/1AreVcvxtd/", "group_type": "data_leads", "members": 189, "quality": "worst", "is_active": True, "owner_name": "Ankara Messi", "owner_url": "https://www.facebook.com/profile.php?id=61579135656972", "admin_1": "Ankara Messi", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "LEADS SeekerS (Data & Leads - Buy & Sell)", "group_url": "https://www.facebook.com/share/g/1TL4Zqs6Ag/", "group_type": "data_leads", "members": 144, "quality": "worst", "is_active": True, "owner_name": "Jonas Weber", "owner_url": "https://www.facebook.com/profile.php?id=61587451465349", "admin_1": "Jonas Weber", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "Elite Data Exchange", "group_url": "https://www.facebook.com/share/g/1Chb8Mad2s/", "group_type": "data_leads", "members": 143, "quality": "worst", "is_active": True, "owner_name": "RH Raw", "owner_url": "https://www.facebook.com/groups/1210072207859087/user/61567723007853", "admin_1": "RH Raw", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "Data & Leads Exchange", "group_url": "https://www.facebook.com/share/g/1CrmUBpgmz/", "group_type": "data_leads", "members": 117, "quality": "worst", "is_active": True, "owner_name": "Prince Romeo", "owner_url": "https://www.facebook.com/share/1CyNecnKCE/", "admin_1": "Prince Romeo", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "Data Market", "group_url": "https://www.facebook.com/groups/2038615047005174/", "group_type": "data_leads", "members": 115, "quality": "worst", "is_active": True, "owner_name": "Arjun Desai", "owner_url": "https://www.facebook.com/share/1QbtJkUkNc/", "admin_1": "Arjun Desai", "admin_2": "", "admin_3": "", "agent_name": "", "backup_url": ""},
    {"name": "All Data Services", "group_url": "https://www.facebook.com/groups/alldataservices", "group_type": "data_leads", "members": 114, "quality": "worst", "is_active": True, "owner_name": "Soham Sen", "owner_url": "https://www.facebook.com/Subaru.leads/", "admin_1": "Soham Sen", "admin_2": "Franz Bonaparta", "admin_3": "", "agent_name": "Abir, Shafi", "backup_url": ""},
    {"name": "Tech Support Activation Campaigns", "group_url": "https://www.facebook.com/share/g/1DTe7W8Txb/", "group_type": "data_leads", "members": 90, "quality": "worst", "is_active": True, "owner_name": "Franz Bonaparta", "owner_url": "https://www.facebook.com/profile.php?id=61578056373952", "admin_1": "Aditya Debnath", "admin_2": "Franz Bonaparta", "admin_3": "", "agent_name": "Shafi, Rafin", "backup_url": ""},
    {"name": "The Biggest Leads & Data Chain", "group_url": "https://www.facebook.com/groups/1156835372955532", "group_type": "data_leads", "members": 89, "quality": "worst", "is_active": True, "owner_name": "Barney Stinson", "owner_url": "https://www.facebook.com/barney.stinsonn/", "admin_1": "Tomas Wright", "admin_2": "", "admin_3": "", "agent_name": "Tasin", "backup_url": ""},
    {"name": "BM2 Users only", "group_url": "https://www.facebook.com/groups/773286832526924", "group_type": "data_leads", "members": 82, "quality": "worst", "is_active": True, "owner_name": "Kishan Reddy", "owner_url": "https://www.facebook.com/groups/773286832526924/user/61579509471409", "admin_1": "Kishan Reddy", "admin_2": "", "admin_3": "", "agent_name": "Tanjnil", "backup_url": ""},
    {"name": "HOME OWNER LEADS GENERATION (BUY & SALES)", "group_url": "https://www.facebook.com/groups/1279288166541672", "group_type": "homeowner_db", "members": 56, "quality": "worst", "is_active": True, "owner_name": "Mk Chowdhury", "owner_url": "https://www.facebook.com/", "admin_1": "Mk Chowdhury", "admin_2": "", "admin_3": "", "agent_name": "Iram", "backup_url": ""},
    {"name": "Lead Zone | Verified Leads & Data", "group_url": "https://www.facebook.com/share/g/1HKV512JXN/", "group_type": "data_leads", "members": 36, "quality": "worst", "is_active": True, "owner_name": "Muhammad Nawaz", "owner_url": "https://www.facebook.com/profile.php?id=61583739080659", "admin_1": "Murtasim Khan", "admin_2": "", "admin_3": "", "agent_name": "Tanvir", "backup_url": ""},
    {"name": "Global Email Database", "group_url": "https://www.facebook.com/groups/747503927990122", "group_type": "data_leads", "members": 33, "quality": "worst", "is_active": True, "owner_name": "Kishan Reddy", "owner_url": "https://www.facebook.com/groups/773286832526924/user/61579509471409", "admin_1": "Kishan Reddy", "admin_2": "", "admin_3": "", "agent_name": "Tanjnil", "backup_url": ""},
    {"name": "Email Marketing Sending System, Blaster & Vendor Community", "group_url": "https://www.facebook.com/share/g/18SBPtfVXe/", "group_type": "other_business", "members": 29, "quality": "worst", "is_active": True, "owner_name": "Sharaf Mahbub", "owner_url": "https://www.facebook.com/share/1DqyJTvG3Z/", "admin_1": "Sharaf Mahbub", "admin_2": "", "admin_3": "", "agent_name": "Siam", "backup_url": ""},
    {"name": "Lead Booster Market", "group_url": "https://www.facebook.com/share/g/1EaKsu6abP/", "group_type": "data_leads", "members": 27, "quality": "worst", "is_active": True, "owner_name": "Alice Khanna", "owner_url": "https://www.facebook.com/profile.php?id=61588031055448", "admin_1": "Alice Khanna", "admin_2": "", "admin_3": "", "agent_name": "Rohan", "backup_url": ""},
    {"name": "Telemarketing Data provide (Dialer/VOIP/Route)", "group_url": "https://www.facebook.com/groups/2186082048836404/", "group_type": "telemarketing", "members": 26, "quality": "worst", "is_active": True, "owner_name": "Arjun Mehta", "owner_url": "https://www.facebook.com/profile.php?id=61584890812694", "admin_1": "Nooru", "admin_2": "Towhid Tonmoy", "admin_3": "", "agent_name": "Tonmoy", "backup_url": ""},
    {"name": "Infinity Data & Leads Arena", "group_url": "https://www.facebook.com/groups/26595131253459793/", "group_type": "data_leads", "members": 22, "quality": "worst", "is_active": True, "owner_name": "Eliza Leads", "owner_url": "https://www.facebook.com/groups/26595131253459793/user/61579456994748", "admin_1": "Eliza Leads", "admin_2": "", "admin_3": "", "agent_name": "Nasrin", "backup_url": ""},
    {"name": "Data Blastwave Kolkata", "group_url": "https://www.facebook.com/groups/957386096833290/", "group_type": "data_leads", "members": 19, "quality": "worst", "is_active": True, "owner_name": "Eliza Leads", "owner_url": "https://www.facebook.com/groups/957386096833290/user/61579456994748/", "admin_1": "Eliza Leads", "admin_2": "", "admin_3": "", "agent_name": "Nasrin", "backup_url": ""},
    {"name": "Elite SMTP, Mail API, RDP, TFN Portal", "group_url": "https://www.facebook.com/share/g/18gTyoLxgo/", "group_type": "data_leads", "members": 17, "quality": "worst", "is_active": True, "owner_name": "Maria Petrova", "owner_url": "https://www.facebook.com/groups/1602104737742262/user/61578476077323", "admin_1": "Maria Petrova", "admin_2": "", "admin_3": "", "agent_name": "Nabila", "backup_url": ""},
    {"name": "Homeowner Data and Leads Expert (USA | UK | Australia | Canada | UAE)", "group_url": "https://www.facebook.com/groups/1575523376852741/", "group_type": "homeowner_db", "members": 17, "quality": "worst", "is_active": True, "owner_name": "Arjun Mehta", "owner_url": "https://www.facebook.com/profile.php?id=61584890812694", "admin_1": "Nooru", "admin_2": "Towhid Tonmoy", "admin_3": "", "agent_name": "Tonmoy", "backup_url": ""},
    {"name": "Voip & Dialer Professionals Network", "group_url": "https://www.facebook.com/groups/1008778818139751/", "group_type": "telemarketing", "members": 10, "quality": "worst", "is_active": True, "owner_name": "M D Ibrahim", "owner_url": "https://www.facebook.com/", "admin_1": "M D Ibrahim", "admin_2": "", "admin_3": "", "agent_name": "Ibrahim", "backup_url": ""},
    {"name": "TeleReach Global", "group_url": "https://www.facebook.com/groups/25560886990250913", "group_type": "telemarketing", "members": 9, "quality": "worst", "is_active": True, "owner_name": "Tomas Wright", "owner_url": "https://www.facebook.com/tomas.wright.2025/", "admin_1": "Tomas Wright", "admin_2": "", "admin_3": "", "agent_name": "Fahim", "backup_url": ""},
    {"name": "OutBound Campaign Data", "group_url": "", "group_type": "data_leads", "members": 7, "quality": "worst", "is_active": True, "owner_name": "Robert Simons", "owner_url": "", "admin_1": "Robert Simons", "admin_2": "", "admin_3": "", "agent_name": "Shuvo", "backup_url": ""},
    {"name": "PRO EMAIL GROWTH HUB", "group_url": "https://www.facebook.com/share/g/1AJ9GqU9wG/", "group_type": "data_leads", "members": 6, "quality": "worst", "is_active": True, "owner_name": "Leon D Cruz", "owner_url": "https://www.facebook.com/profile.php?id=61582746087903", "admin_1": "Leon D Cruz", "admin_2": "", "admin_3": "", "agent_name": "Rohan", "backup_url": ""},
    {"name": "Bulk Contact Data Buyers & Sellers", "group_url": "https://www.facebook.com/groups/1689168295314317", "group_type": "data_leads", "members": 6, "quality": "worst", "is_active": True, "owner_name": "M D Ibrahim", "owner_url": "https://www.facebook.com/", "admin_1": "M D Ibrahim", "admin_2": "", "admin_3": "", "agent_name": "Ibrahim", "backup_url": ""},
    {"name": "Homeowner Leads Alliance", "group_url": "https://www.facebook.com/groups/1303592068372099", "group_type": "homeowner_db", "members": 6, "quality": "worst", "is_active": True, "owner_name": "M D Ibrahim", "owner_url": "", "admin_1": "M D Ibrahim", "admin_2": "", "admin_3": "", "agent_name": "Ibrahim", "backup_url": ""},
    {"name": "Data & Lead Providers", "group_url": "", "group_type": "data_leads", "members": 5, "quality": "worst", "is_active": True, "owner_name": "Robert Simons", "owner_url": "", "admin_1": "Robert Simons", "admin_2": "", "admin_3": "", "agent_name": "Shuvo", "backup_url": ""},
    {"name": "Data & Leads World", "group_url": "https://www.facebook.com/groups/969880132467012", "group_type": "data_leads", "members": 2, "quality": "worst", "is_active": True, "owner_name": "Robert Simons", "owner_url": "", "admin_1": "Robert Simons", "admin_2": "", "admin_3": "", "agent_name": "Shuvo", "backup_url": ""},
]


class Command(BaseCommand):
    help = 'Seed 64 Facebook groups (skips if already seeded)'

    def handle(self, *args, **options):
        existing = FacebookGroup.objects.count()
        if existing >= len(GROUPS):
            self.stdout.write(self.style.WARNING(
                f'Already have {existing} groups — skipping seed.'
            ))
            return

        created = 0
        for data in GROUPS:
            _, new = FacebookGroup.objects.get_or_create(
                name=data['name'],
                defaults=data,
            )
            if new:
                created += 1

        self.stdout.write(self.style.SUCCESS(
            f'Seeded {created} Facebook groups ({FacebookGroup.objects.count()} total).'
        ))
