# Generated by Django 6.0.5 on 2026-05-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_lead', models.DecimalField(decimal_places=2, max_digits=8)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('REPLACED', 'Replaced'), ('REFUNDED', 'Refunded')], default='ACTIVE', max_length=20)),
                ('client_status', models.CharField(choices=[('NEW', 'New'), ('CONTACTED', 'Contacted'), ('CONVERTED', 'Converted'), ('BAD', 'Bad')], default='NEW', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReplacementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('WRONG_NUMBER', 'Wrong Number'), ('DUPLICATE', 'Duplicate'), ('UNREACHABLE', 'Unreachable'), ('UNDER_AGE', 'Under Age'), ('OUT_OF_AREA', 'Out of Area')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('niche', models.CharField(choices=[('solar-usa', 'Solar USA'), ('solar-uk', 'Solar UK'), ('solar-ca', 'Solar Canada'), ('solar-au', 'Solar Australia'), ('sweeps-auto', 'Sweepstakes Auto'), ('sweeps-health', 'Sweepstakes Health'), ('sweeps-medicare', 'Sweepstakes Medicare'), ('sweeps-home', 'Sweepstakes Home'), ('sweeps-life', 'Sweepstakes Life'), ('sweeps-debt', 'Sweepstakes Debt'), ('sweeps-generic', 'Sweepstakes Generic')], max_length=20)),
                ('campaign_id', models.CharField(blank=True, max_length=255)),
                ('ad_set_id', models.CharField(blank=True, max_length=255)),
                ('source_page', models.URLField(blank=True)),
                ('utm_source', models.CharField(blank=True, max_length=255)),
                ('utm_medium', models.CharField(blank=True, max_length=255)),
                ('utm_campaign', models.CharField(blank=True, max_length=255)),
                ('utm_content', models.CharField(blank=True, max_length=255)),
                ('utm_term', models.CharField(blank=True, max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='US', max_length=2)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_homeowner', models.BooleanField(blank=True, null=True)),
                ('monthly_bill', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('credit_score', models.CharField(blank=True, max_length=20)),
                ('roof_type', models.CharField(blank=True, max_length=50)),
                ('roof_age', models.PositiveIntegerField(blank=True, null=True)),
                ('solar_timeline', models.CharField(blank=True, max_length=50)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currently_insured', models.BooleanField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('total_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quality_score', models.PositiveIntegerField(default=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('trusted_form_cert_url', models.URLField(blank=True)),
                ('tcpa_consent_text', models.TextField(blank=True)),
                ('tcpa_consent_at', models.DateTimeField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_on_dnc', models.BooleanField(default=False)),
                ('dnc_checked_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('AVAILABLE', 'Available'), ('ALLOCATED', 'Allocated'), ('SOLD', 'Sold'), ('REPLACED', 'Replaced'), ('DUPLICATE', 'Duplicate'), ('REJECTED', 'Rejected')], default='NEW', max_length=20)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='leads.lead')),
            ],
        ),
    ]
