# Generated by Django 6.0.5 on 2026-05-15 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('clients', '0001_initial'),
        ('leads', '0001_initial'),
        ('sweepstakes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sweepstakes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sweepstakes.sweepstakes'),
        ),
        migrations.AddField(
            model_name='leadallocation',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='clients.client'),
        ),
        migrations.AddField(
            model_name='leadallocation',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadallocation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='billing.order'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='allocation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_request', to='leads.leadallocation'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='clients.client'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replacement_requests', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='replacement_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_for', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='replacementrequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_replacements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['niche', 'status'], name='leads_lead_niche_dbd940_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='leads_lead_created_302c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['email', 'niche'], name='leads_lead_email_f1d7a7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['phone', 'niche'], name='leads_lead_phone_2e8745_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='leadallocation',
            unique_together={('lead', 'client')},
        ),
    ]
