# Generated by Django 6.0.5 on 2026-05-20 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='niche',
            field=models.CharField(choices=[('solar-usa', 'Solar USA'), ('solar-uk', 'Solar UK'), ('solar-ca', 'Solar Canada'), ('solar-au', 'Solar Australia'), ('sweeps-auto', 'Sweepstakes Auto'), ('sweeps-health', 'Sweepstakes Health'), ('sweeps-medicare', 'Sweepstakes Medicare'), ('sweeps-home', 'Sweepstakes Home'), ('sweeps-life', 'Sweepstakes Life'), ('sweeps-debt', 'Sweepstakes Debt'), ('sweeps-generic', 'Sweepstakes Generic'), ('homeowner-usa', 'Homeowner USA'), ('homeowner-uk', 'Homeowner UK'), ('homeowner-ca', 'Homeowner Canada'), ('homeowner-au', 'Homeowner Australia'), ('payday-usa', 'Payday USA'), ('payday-uk', 'Payday UK'), ('payday-ca', 'Payday Canada'), ('payday-au', 'Payday Australia')], max_length=20),
        ),
    ]
