# Generated by Django 6.0.5 on 2026-05-15 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sweepstakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('niche', models.CharField(choices=[('solar-usa', 'Solar USA'), ('solar-uk', 'Solar UK'), ('solar-ca', 'Solar Canada'), ('solar-au', 'Solar Australia'), ('sweeps-auto', 'Sweepstakes Auto'), ('sweeps-health', 'Sweepstakes Health'), ('sweeps-medicare', 'Sweepstakes Medicare'), ('sweeps-home', 'Sweepstakes Home'), ('sweeps-life', 'Sweepstakes Life'), ('sweeps-debt', 'Sweepstakes Debt'), ('sweeps-generic', 'Sweepstakes Generic')], max_length=20)),
                ('prize_title', models.CharField(max_length=255)),
                ('prize_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prize_image', models.ImageField(blank=True, upload_to='sweepstakes/')),
                ('official_rules_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('draw_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('DRAWN', 'Drawn')], default='DRAFT', max_length=10)),
                ('total_entries', models.PositiveIntegerField(default=0)),
                ('winner_drawn_at', models.DateTimeField(blank=True, null=True)),
                ('prize_delivered_at', models.DateTimeField(blank=True, null=True)),
                ('target_state', models.CharField(blank=True, max_length=100)),
                ('min_age', models.PositiveIntegerField(default=18)),
                ('winner_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_sweepstakes', to='leads.lead')),
            ],
        ),
    ]
