# Generated by Django 6.0.5 on 2026-05-20 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('group_url', models.URLField(blank=True, max_length=1000)),
                ('group_type', models.CharField(choices=[('data_leads', 'Data and leads'), ('cpa_affiliate', 'CPA/Affiliate Database'), ('homeowner_db', 'Homeowner database'), ('telemarketing', 'Telemarketing or Number leads'), ('email_tech', 'Email or Tech support'), ('other_business', 'Other business group'), ('review', 'Review Group')], default='data_leads', max_length=30)),
                ('members', models.PositiveIntegerField(default=0)),
                ('quality', models.CharField(choices=[('very_good', 'Very good'), ('good', 'Good'), ('average', 'Average'), ('below_average', 'Below Average'), ('bad', 'Bad'), ('worst', 'Worst')], default='average', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_url', models.URLField(blank=True, max_length=1000)),
                ('admin_1', models.CharField(blank=True, max_length=255)),
                ('admin_2', models.CharField(blank=True, max_length=255)),
                ('admin_3', models.CharField(blank=True, max_length=255)),
                ('agent_name', models.CharField(blank=True, max_length=255)),
                ('backup_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_fb_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facebook Group',
                'verbose_name_plural': 'Facebook Groups',
                'ordering': ['-members'],
            },
        ),
    ]
