# Generated by Django 6.0.5 on 2026-05-15 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('SOLD', 'Sold'), ('LOST', 'Lost'), ('FOLLOW_UP', 'Follow Up')], default='ASSIGNED', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_leads', models.PositiveIntegerField(default=20)),
                ('target_revenue', models.DecimalField(decimal_places=2, default='1000.00', max_digits=10)),
                ('commission', models.DecimalField(decimal_places=3, default='0.100', max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('ANSWERED', 'Answered'), ('NO_ANSWER', 'No Answer'), ('VOICEMAIL', 'Voicemail'), ('WRONG_NUMBER', 'Wrong Number'), ('CALLBACK', 'Callback'), ('SOLD', 'Sold')], max_length=20)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('next_follow_up', models.DateTimeField(blank=True, null=True)),
                ('called_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='agents.agent')),
            ],
        ),
    ]
