# Generated by Django 6.0.5 on 2026-05-15 10:50

import apps.clients.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('billing_address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('api_key', models.CharField(default=apps.clients.models._generate_api_key, max_length=64, unique=True)),
                ('notify_email', models.BooleanField(default=True)),
                ('notify_sms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niche', models.CharField(choices=[('solar-usa', 'Solar USA'), ('solar-uk', 'Solar UK'), ('solar-ca', 'Solar Canada'), ('solar-au', 'Solar Australia'), ('sweeps-auto', 'Sweepstakes Auto'), ('sweeps-health', 'Sweepstakes Health'), ('sweeps-medicare', 'Sweepstakes Medicare'), ('sweeps-home', 'Sweepstakes Home'), ('sweeps-life', 'Sweepstakes Life'), ('sweeps-debt', 'Sweepstakes Debt'), ('sweeps-generic', 'Sweepstakes Generic')], max_length=20)),
                ('leads_per_period', models.PositiveIntegerField()),
                ('price_per_lead', models.DecimalField(decimal_places=2, max_digits=8)),
                ('billing_period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=10)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tx_type', models.CharField(choices=[('TOP_UP', 'Top Up'), ('LEAD_PURCHASE', 'Lead Purchase'), ('REFUND', 'Refund'), ('CREDIT_ADJUSTMENT', 'Credit Adjustment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.wallet')),
            ],
        ),
    ]
